Add package.json and update installation directions
Akkjon/minecraft-scraper pull request #1
Opened 2022-02-02 07:43 UTC by spinfal

2022-02-02 08:23 UTC, Akkjon commented on .gitignore
> +package-lock.json
I would prefer the package-lock.json to be removed from the .gitignore as it reduces errors by installing the exact same version of dependencies everytime and sometimes makes debugging easier.

2022-02-02 11:04 UTC, Akkjon requested changes

2022-02-02 11:04 UTC, Akkjon commented on Readme.md
> +npm start dev
it is `npm run dev`

2022-02-02 11:04 UTC, Akkjon commented on .gitignore
> +package-lock.json
I would prefer the package-lock.json to be removed from the .gitignore as it reduces errors by installing the exact same version of dependencies everytime and sometimes makes debugging easier.

2022-02-03 07:54 UTC, spinfal reviewed
Removed package-lock.json from .gitignore & changed "npm start dev" to "npm run dev"

2022-02-03 09:12 UTC, Akkjon approved these changes

2022-02-03 09:13 UTC, merged